### PR TITLE
Watch nested addons when using new Watchman versions

### LINKED ISSUE #25: Changes to local addon dependencies aren't detected when using newer versions of Watchman
prior art: #12 

Use case: our developers occasionally make changes to our internal Ember Addons that are consumed by our host app, and they do so while running the _host app's_ dev server instead of the addon's. This worked fine in Watchman v4.9.0, but the recent changes to the versioning format broke it and now changes to the addon do not trigger a rebuild of the host app.

Most of the semver-related issues were fixed in https://github.com/ember-cli/watch-detector/pull/13, but this one remained. Since that PR removed most of the version checks (and the corresponding test), I'm going to open a PR that finishes the job and removes the one remaining version check.

### PR DESCRIPTION
**Pull request by ginomiglio**
Similar to https://github.com/ember-cli/watch-detector/pull/13, the semver check here is no longer valid and was preventing newer versions of Watchman from properly watching nested addons.

This was the last remaining usage of `semver` so I've also removed it from `package.json`.

Fixes https://github.com/ember-cli/watch-detector/issues/25.

### CODE REVIEW

**Comment by ginomiglio** [comment]
Looks like this is a duplicate of #23, though that PR doesn't clean up the leftover `semver` dependency so I'll leave this one open.

@rwjblue do you have a chance to review this week?

**Comment by bloemendal** [comment]
Any chance of this getting merged? We are running into the bug reported and fixed in #23

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
@ginomiglio - Would you mind fixing up the test cases? I think they might just need to be deleted?

**Comment by ginomiglio** [comment]
@rwjblue I think those failures are unrelated to my change – #34 should fix them though

**Comment by ginomiglio** [comment]
Thanks @bertdeblock and @rwjblue – can we cut a release too?

**Pull request merged**
